title: Sehen Dmytro
logo: https://osvitoria.media/wp-content/uploads/2020/04/353974-PBME6B-537.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
